# Generated by Django 3.1.1 on 2020-10-02 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201002_1135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='User',
        ),
    ]
