[tool.poetry]
name = "GreyWolf_Task_Manager"
version = "0.0.1"
description = "Task_Manager"
authors = ["GreyGreyWolf"]
packages = [
  {include = "task_manager"},
  ]

[tool.poetry.dependencies]
python = "^3.6"
django = "^3.1.1"
rollbar = "^0.15.1"
requests = "^2.24.0"
python-dotenv = "^0.14.0"
django-bootstrap4 = "^2.2.0"
heroku = "^0.1.4"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.3"
pytest = "^6.0.1"
pytest-cov = "^2.10.1"
coverage = "^5.2.1"
gunicorn = "^20.0.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
