# Generated by Django 3.1.2 on 2020-10-05 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='status_image/')),
            ],
            options={
                'verbose_name': 'Image ',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.RenameModel(
            old_name='Task_status',
            new_name='Taskstatus',
        ),
        migrations.DeleteModel(
            name='StatusImage',
        ),
        migrations.AddField(
            model_name='status_image',
            name='status_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_name', to='tasks.taskstatus'),
        ),
    ]
