# Generated by Django 3.1.2 on 2020-10-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20201005_1653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status_image',
        ),
    ]
